finalprojectSD340/Models/Task.cs
using System.ComponentModel.DataAnnotations;

namespace finalprojectSD340.Models
{
    public class Task
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsCompleted { get; set; } = false;
        [Display(Name = "Completion Percentage")]
        public int CompletionPercentage { get; set; } = 0;
        public int ProjectId { get; set; }
        public Project Project { get; set; }
        public string? DeveloperId { get; set; }
        public ApplicationUser? Developer { get; set; }
        public ICollection<Comment> Comments { get; set; }
        public ICollection<Notification> Notifications { get; set; }
        public Priority Priority { get; set; }
        public DateTime Deadline { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime CompleteDate { get; set; }
        public double TaskCost { get; set; }
        public bool ReminderSent { get; set; } = false;
        public bool DeadlineNotificationSent { get; set; } = false;
        public bool CompleteNotificationSent { get; set; } = false;

        public Task()
        {
            Comments = new HashSet<Comment>();
            Notifications = new HashSet<Notification>();
        }

    }
}

finalprojectSD340/Controllers/DevController.cs
using finalprojectSD340.Data;
using finalprojectSD340.HelperClasses;
using finalprojectSD340.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace finalprojectSD340.Controllers
{

    public class DevController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly ApplicationDbContext _db;
        private readonly TaskHelper _taskHelper;
        private readonly NotificationHelper _notifHelper;
        
        public DevController(ApplicationDbContext db, RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager)
        {
            _db = db;
            _userManager = userManager;
            _roleManager = roleManager;
            _taskHelper = new TaskHelper(db, userManager);
            _notifHelper = new NotificationHelper(_db, _userManager, _roleManager);
        }

        // GET: DevController
        [Authorize(Roles = "Developer, Admin")]
        public async Task<ActionResult> DeveloperDashboard()
        {
            try
            {
                string userName = User.Identity.Name;
                
                ApplicationUser user = _db.Users.First(u => u.UserName == userName);
                string deadlineNotifChecker = await _notifHelper.CheckDeadlineNotification(user.Id);
                if (deadlineNotifChecker != "Success")
                {
                    throw new Exception(deadlineNotifChecker);
                }

                ViewBag.Notifications = _db.Notifications.Where(n => !n.IsOpened && n.UserId == user.Id).ToList().Count;

                return View();
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", new { Message = ex.Message, Action = "DeveloperDashboard" });
            }
        }

        [Authorize(Roles = "Developer, Admin")]
        public async Task<IActionResult> DeveloperNotifications()
        {
            try
            {
                string userName = User.Identity.Name;
                ApplicationUser user = await _userManager.FindByEmailAsync(userName);
                List<Notification> unopenedNotifications = _db.Notifications
                    .Include(p => p.Project)
                    .Where(n => n.UserId == user.Id && !n.IsOpened)
                    .OrderByDescending(n => n.NotificationDate)
                    .ToList();

                List<Notification> openedNotifications = _db.Notifications
                    .Include(p => p.Project)
                    .Where(n => n.UserId == user.Id && n.IsOpened)
                    .OrderBy(n => n.NotificationDate)
                    .ToList();

                ViewBag.OpenedNotifications = openedNotifications;

                if (unopenedNotifications.Count == 0 && openedNotifications.Count == 0)
                {
                    ViewBag.Any = 1;
                }

                return View(unopenedNotifications);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", new { Message = ex.Message, Action = "DeveloperNotifications" });
            }
        }

        [Authorize(Roles = "Developer, Admin")]
        public async Task<IActionResult> DeveloperTasks()
        {
            try
            {
                string userName = User.Identity.Name;
                ApplicationUser dev = await _userManager.FindByEmailAsync(userName);

                List<Models.Task> devTasks = _db.Tasks
                    .Include(x => x.Project)
                    .Where(t => t.DeveloperId == dev.Id)
                    .ToList();

                return View(devTasks);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", new { Message = ex.Message, Action = "DeveloperTasks" });
            }
        }

        [Authorize(Roles = "Developer, Project Manager, Admin")]
        [HttpPost]
        public async Task<IActionResult> CompleteTask(int taskId)
        {
            try
            {
                string userName = User.Identity.Name;
                ApplicationUser user = await _userManager.FindByEmailAsync(userName);
                Models.Task task = _db.Tasks.First(t => t.Id == taskId);

                if (task == null)
                    return RedirectToAction("PMProjectDetails", "PM", new { id = task.ProjectId, message = "Task was not found." });

                if (task.DeveloperId == null)
                    return RedirectToAction("PMProjectDetails", "PM", new { id = task.ProjectId, message = "There is no developer assigned to this task." });

                if (task.IsCompleted)
                {
                    return RedirectToAction("PMProjectDetails", "PM", new { id = task.ProjectId, message = "Task has been completed." });
                }

                if (!task.IsCompleted)
                {
                    task.IsCompleted = true;
                    task.CompletionPercentage = 100;
                    task.CompleteDate = DateTime.Now;
                    await _taskHelper.CalculateTaskCost(taskId);
                }
                bool CheckDevRole = await _userManager.IsInRoleAsync(user, "Developer");

                if (CheckDevRole != true)
                {
                    await _db.SaveChangesAsync();
                    return RedirectToAction("PMProjectDetails", "PM", new { id = task.ProjectId });
                }

                if (!task.CompleteNotificationSent)
                {
                    string completeNotifChecker = await _notifHelper.CreateCompleteTaskNotification(user.Id, task.Id);
                    if (completeNotifChecker != "Success")
                    {
                        throw new Exception(completeNotifChecker);
                    }
                }

                await _db.SaveChangesAsync();

                return RedirectToAction("DeveloperTasks");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", new { Message = ex.Message, Action = "DeveloperTasks" });
            }
        }

        [Authorize(Roles = "Developer, Admin")]
        [HttpPost]
        public async Task<IActionResult> TaskPercentage(int percentInput, int taskId)
        {
            try
            {
                if (percentInput == null || taskId == null)
                    return BadRequest();

                Models.Task task = _db.Tasks.First(t => t.Id == taskId);

                if (task == null)
                    return NotFound();

                task.CompletionPercentage = percentInput;

                await _db.SaveChangesAsync();

                if (percentInput == 100)
                {
                    await CompleteTask(taskId);
                }

                return RedirectToAction("DeveloperTasks");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", new { Message = ex.Message, Action = "DeveloperTasks" });
            }
        }

        public IActionResult TaskView(int taskId)
        {
            Models.Task task = _db.Tasks
                .Include(t => t.Developer)
                .Include(t => t.Project)
                .Include(t => t.Comments)
                .First(t => t.Id == taskId);

            return View(task);
        }

        [Authorize(Roles = "Developer, Admin")]
        [HttpPost]
        public async Task<IActionResult> MakeComment(int? taskId, string? comment, bool urgent)
        {
            try
            {
                string userName = User.Identity.Name;
                ApplicationUser commenter = await _userManager.FindByEmailAsync(userName);

                if (taskId == null)
                    return NotFound();

                Models.Task task = _db.Tasks.First(t => t.Id == taskId);

                if (string.IsNullOrWhiteSpace(comment))
                    return RedirectToAction("TaskView", task.Id);

                Comment newComment = new()
                {
                    Body = comment,
                    DateCreated = DateTime.Now,
                    Developer = commenter,
                    DeveloperId = commenter.Id,
                    Task = task,
                    TaskId = task.Id
                };

                if (urgent)
                {
                    newComment.IsUrgent = true;
                    string urgentSender = await _notifHelper.UrgentNotification(commenter.Id, task.Id, newComment, NotificationType.Urgent);

                    if (urgentSender != "Success")
                    {
                        throw new Exception(urgentSender);
                    }
                }

                commenter.Comments.Add(newComment);
                task.Comments.Add(newComment);
                _db.Comments.Add(newComment);

                await _userManager.UpdateAsync(commenter);
                await _db.SaveChangesAsync();

                return RedirectToAction("TaskView", new { taskId = task.Id });
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", new { Message = ex.Message, Action = "DeveloperTasks" });
            }
        }

        [HttpPost]
        public async Task<IActionResult> OpenNotification(int id)
        {
            try
            {
                string openCheck = await _notifHelper.OpenNotification(id);

                if (openCheck != "Success")
                {
                    throw new Exception(openCheck);
                }

                return RedirectToAction("DeveloperNotifications");
            }
            catch (Exception ex)
            {

finalprojectSD340/Views/Dev/DeveloperDashboard.cshtml
@{
    ViewData["Title"] = "DevDashboard";
}

<div class="text-center">
    <h1>Dev Dashboard</h1>

    <h4>Notifications! <a asp-action="DeveloperNotifications">@ViewBag.Notifications</a></h4>

    <a asp-action="DeveloperTasks">View your Tasks</a>

    <br />

    <a asp-action="DeveloperNotifications">View your Notifications</a>
</div>

finalprojectSD340/Views/Dev/DeveloperNotifications.cshtml
@model IEnumerable<finalprojectSD340.Models.Notification>

@{
    ViewData["Title"] = "DeveloperNotifications";
}

<h1>Notifications</h1>

<a asp-action="DeveloperDashboard">Back</a>

@if (ViewBag.Any == 1)
{
    <div>
        <h4>You have no notifications</h4>
    </div>
}

<h3>Unopened</h3>
<table class="table">
    <thead>
        <tr>
            <th>
                Type
            </th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model) {
            <tr>
                <td>
                    @item.Type - @item.NotificationDate.Date
                </td>
                <td></td>
                <td></td>                
                <td>
                    <button type="button" type="submit" class="collapsible">View Notification</button>
                    <div class="content">
                        <p>Title: @item.Title</p>
                        <p>Content: @item.Body</p>
                        <p>Project: @item.Project.Name</p>
                    </div>
                </td>
                <td>
                    <form asp-action="OpenNotification" asp-route-id="@item.Id" method="post">
                        <button type="submit">Mark as Opened</button>
                    </form> 
                    <hr>
                    <form asp-action="DeleteNotification" asp-route-notificationId="@item.Id" method="post">
                        <button type="submit">Delete</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

<h3>Opened</h3>

<p>
    <a asp-controller="Dev" asp-action="DeveloperDashboard">Developer Dashboard</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                Project
            </th>
            <th>
                Type
            </th>
            <th>
                Date
            </th>
            <th>
                Title
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in ViewBag.OpenedNotifications) {
            <tr>
                <td>
                    @item.Project.Name
                </td>
                <td>
                    @item.Type - @item.NotificationDate.Date
                </td>
                <td>
                    @item.NotificationDate.Date
                </td>
                <td>
                    @item.Title
                </td>
                <td>
                    @item.Body
                </td>
                <td>
                    <form asp-action="DeleteNotification" asp-route-notificationId="@item.Id" method="post">
                        <button type="submit">Delete</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

<script>
    var coll = document.getElementsByClassName("collapsible");
    var i;

    for (i = 0; i < coll.length; i++) {
      coll[i].addEventListener("click", function() {
        this.classList.toggle("active");
        var content = this.nextElementSibling;
        if (content.style.maxHeight){
          content.style.maxHeight = null;
        } else {
          content.style.maxHeight = content.scrollHeight + "px";
        } 
      });
    }
</script>

finalprojectSD340/Views/Dev/DeveloperTasks.cshtml
@model IEnumerable<finalprojectSD340.Models.Task>

@{
    ViewData["Title"] = "DeveloperTasks";
}

<h1>Tasks</h1>

<a asp-action="DeveloperDashboard">Back</a>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CompletionPercentage)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Project)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Priority)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Deadline)
            </th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                <div style="display:flex;flex-flow=row">
                    @Html.DisplayFor(modelItem => item.CompletionPercentage)
                    @if (!item.IsCompleted)
                    {
                        <form asp-action="TaskPercentage" asp-route-taskId="@item.Id" method="post" style="margin-left:1rem">
                            <input name="percentInput" id="percentInput" value="@item.CompletionPercentage" type="range" min="0" max="100" step="5" oninput="this.nextElementSibling.value = this.value">
                            <output style="margin:0 1rem">@item.CompletionPercentage</output>
                            <button type="submit">Adjust</button>
                        </form>
                    }
                </div>
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Project.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Priority)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Deadline)
            </td>
            <td>
                @if (!item.IsCompleted)
                {
                    <form asp-action="CompleteTask" asp-route-taskId="@item.Id" method="post">
                        <button type="submit">Complete</button>
                    </form>
                }
            </td>
            <td>
                <a asp-action="TaskView" asp-route-taskId="@item.Id">View Task</a>
            </td>
        </tr>
}
    </tbody>
</table>

finalprojectSD340/Views/Dev/TaskView.cshtml
@model finalprojectSD340.Models.Task

@{
    ViewData["Title"] = "TaskView";
}

<h1>View Task</h1>

<a asp-action="DeveloperTasks">Back</a>

@if (Model.IsCompleted)
{
    <h3 style="color:green">Complete!</h3>
}

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CompletionPercentage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CompletionPercentage)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Project)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Project.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Developer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Developer.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Priority)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Priority)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Deadline)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Deadline)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="DeveloperTasks">Back to List</a>
</div>
@if (!Model.IsCompleted)
{
    <div>
        <h5>Send Urgent Note</h5>
        <form asp-action="MakeComment" asp-route-taskId="@Model.Id" asp-route-urgent="true" method="post">
            <textarea name="comment" style="width:400px;height:100px"></textarea>
            <br>
            <button type="submit">Send</button>
        </form>
    </div>
}
else
{
    <div style="margin-top:2rem">
        <h5>Leave A Comment</h5>
        <form asp-action="MakeComment" asp-route-taskId="@Model.Id" method="post">
            <textarea name="comment" style="width:400px;height:100px"></textarea>
            <br>
            <button type="submit">Post</button>
        </form>
    </div>

    <hr />

    <div style="width:50%;margin:0 auto; margin-top:5rem">
        <h3>Comments:</h3>
        @foreach(var i in Model.Comments)
        {
            <div style="border:1px solid lightgray;border-inline:hidden;margin-bottom:3.5rem;background:linear-gradient(to right, rgb(255,255,255), rgb(240,240,240), rgb(255,255,255))">
                @if (i.Developer != null)
                {
                    <h6>User: @i.Developer.Email</h6>
                }               
                <p style="color:lightgrey; font-size:0.8rem; margin-bottom:0.5rem;">Post Date: @i.DateCreated.ToShortDateString()</p>
                <div style="border:1px solid lightgrey; border-radius:8px; padding:1rem; width:80%; margin:0 auto 2rem; background:white;">
                    <p style="margin-bottom:2rem">@i.Body</p>
                </div>
            </div>
        }
    </div>
}